-- executar na conta sb_readonly

/*DROP VIEW view_linhasVenda_promocoes;
DROP VIEW view_linhasvenda;
DROP VIEW view_vendas;
DROP VIEW view_promocoes;
DROP VIEW view_produtos;
DROP VIEW view_categorias;
DROP VIEW view_clientes;*/

CREATE OR REPLACE VIEW "SB_READONLY"."VIEW_PROMOCOES" ("SRC_ID", "SRC_NAME", "SRC_DESCRIPTION", "SRC_START_DATE", "SRC_END_DATE", "SRC_CTTP1", "SRC_CTTP2", "SRC_REDUCTION", "SRC_ON_OUTDOOR", "SRC_ON_TV", "SRC_LAST_CHANGED") AS 
SELECT "COD_PROMO","NOME","DESCR","DATA_INIC","DATA_FIM","CTTP1","CTTP2","REDUCAO","CARTAZ","ANUNCIO","LAST_CHANGED" FROM sb_tables.t_promocoes;

CREATE OR REPLACE VIEW "SB_READONLY"."VIEW_PRODUTOS" ("SRC_ID", "SRC_NAME", "SRC_STOCK", "SRC_UNIT_PRICE", "SRC_WIDTH", "SRC_HEIGHT", "SRC_DEPTH", "SRC_DESCRIPTION", "SRC_PACK_TYPE", "SRC_CALORIES_100G", "SRC_WEIGHT", "SRC_LIQ_WEIGHT", "SRC_COST", "SRC_BRAND", "SRC_BAR_CODE", "SRC_CATEGORY_ID", "SRC_LAST_CHANGED") AS 
SELECT "COD_PRODUTO","NOME","QUANT_STOCK","PRECO_UNIT","LARGURA","ALTURA","PROFUNDIDADE","COMPOSICAO","TIPO_EMBALAGEM","CALORIAS_100G","PESO","PESO_LIQ","CUSTO","MARCA","COD_BARRAS","COD_CATEGORIA","LAST_CHANGED" FROM sb_tables.t_produtos;
 
CREATE OR REPLACE VIEW "SB_READONLY"."VIEW_VENDAS" ("SRC_ID", "SRC_SALE_DATE", "SRC_POS", "SRC_EMPLOYEE_ID", "SRC_STORE_ID", "SRC_CUSTOMER_ID", "SRC_LAST_CHANGED") AS 
SELECT "COD_VENDA","DATA","NUM_CAIXA","NUM_FUNC","COD_LOJA","COD_CLIENTE","LAST_CHANGED" FROM sb_tables.t_vendas;

CREATE OR REPLACE VIEW "SB_READONLY"."VIEW_LINHASVENDA" ("SRC_ID", "SRC_SALE_ID", "SRC_PRODUCT_ID", "SRC_QUANTITY", "SRC_PRICE_OF_SALE", "SRC_AMMOUNT_PAID", "SRC_OBS", "SRC_LAST_CHANGED", "SRC_LINE_DATE") AS 
SELECT "COD_LINHA","COD_VENDA","COD_PRODUTO","QUANTIDADE","PRECO_VENDA","PRECO_TOTAL","OBS","LAST_CHANGED","DATA" FROM sb_tables.t_linhasvenda;

CREATE OR REPLACE VIEW "SB_READONLY"."VIEW_LINHASVENDA_PROMOCOES" ("SRC_LINE_ID", "SRC_PROMO_ID", "SRC_LAST_CHANGED") AS 
SELECT "COD_LINHA","COD_PROMO","LAST_CHANGED" FROM sb_tables.t_linhasVenda_promocoes;

CREATE OR REPLACE VIEW "SB_READONLY"."VIEW_CATEGORIAS" ("SRC_ID", "SRC_NAME", "SRC_OBS", "SRC_CREATION_DATE", "SRC_LAST_CHANGED") AS 
SELECT "COD_CATEGORIA","NOME","OBS","DATA_CRIACAO","LAST_CHANGED" FROM sb_tables.t_categ;
 
CREATE OR REPLACE VIEW "SB_READONLY"."VIEW_CLIENTES" ("SRC_ID", "SRC_CARD_NUMBER", "SRC_NAME", "SRC_ADDRESS", "SRC_LOCATION", "SRC_DISTRICT", "SRC_ZIP_CODE", "SRC_PHONE_NR", "SRC_GENDER", "SRC_AGE", "SRC_MARITAL_STATUS", "SRC_LAST_CHANGED") AS 
SELECT "COD_CLIENTE","NUMERO_CARTAO","NOME","MORADA","LOCALIDADE","DISTRITO","CODIGO_POSTAL","TELEFONE","SEXO","IDADE","ESTADO_CIVIL","LAST_CHANGED"  FROM sb_tables.t_clientes;
 

